# Generated by Django 4.0.1 on 2022-02-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False, verbose_name='Is host'),
        ),
    ]
